version: 2
jobs:
  # validate:
  #   working_directory: ~/ami
  #   docker:
  #     - image: hashicorp/packer:1.5.6
  #   steps:
  #     - checkout
  #     - run:
  #         name: Validate
  #         command: packer validate ami.json

  build:
    docker:
      - image: hashicorp/packer:1.5.6
    working_directory: ~/ami
    steps:
      - checkout
      - attach_workspace:
          at: ~/ami
      # - run:
      #     name: install awscli
      #     command: |-
      #       sudo apt update
      #       sudo apt upgrade
      #       sudo apt install curl
      #       sudo apt install unzip
      #       curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #       unzip awscliv2.zip
      #       sudo ./aws/install
      #       aws --version
      - run:
          name: prepare env var
          command: |-
            echo $IS_PRODUCTION
            export AWS_ACCESS_KEY_ID_DEV=${AWS_ACCESS_KEY_ID}
            export AWS_SECRET_ACCESS_KEY_DEV=${AWS_SECRET_ACCESS_KEY}
            export AWS_DEFAULT_REGION_DEV=${AWS_DEFAULT_REGION}
            export AWS_DEV_ACCOUNT=${AWS_DEV_ACCOUNT}
            export AWS_PROD_ACCOUNT=${AWS_PROD_ACCOUNT}
      - run:
          name: validater packer template
          command: |-
            packer validate ami.json
      - run:
          name: build
          command: |-
            packer build ami.json
          # no_output_timeout: 30m

# workflows:
#   version: 2
#   build-and-deploy:
#     jobs:
#       - validate
#       - build-dev-ami:
#           context: csye6225-aws-dev
#           requires:
#             - validate

# "sudo apt-get install mysql-client --fix-missing --fix-broken -y"
